spring:
   r2dbc:
      url: r2dbc:postgresql://localhost:5432/postgres?schema=anime
      username: postgres
      password: 1234

logging:
   level:
      org:
         springframework:
            data:
               r2dbc: DEBUG

server:
   error:
      include-stacktrace: on_param